"""
Report Generator Module
Produces structured compliance reports in Markdown and JSON formats.

Design Decision: Reports are formatted for non-technical safety managers.
Each finding includes the problematic text, what the regulation requires,
and specific corrective action — so the reader can act without needing
to look up OSHA standards themselves.
"""

import json
from datetime import datetime
from typing import Optional

from .analyzer import ComplianceReport, SEVERITY_LEVELS


def generate_markdown_report(report: ComplianceReport) -> str:
    """Generate a professional markdown compliance report."""
    lines = []

    # Header
    lines.append("# Safety Document Compliance Report")
    lines.append("")
    lines.append(f"**Document Analyzed:** {report.document_name}")
    lines.append(f"**Analysis Date:** {report.analysis_date}")
    lines.append(f"**Regulation Standard:** {report.regulation_standard}")
    lines.append(f"**Overall Status:** {_format_status_badge(report.overall_compliance_status)}")
    lines.append("")

    # Executive Summary
    lines.append("---")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.summary)
    lines.append("")

    # Findings Overview
    lines.append("## Findings Overview")
    lines.append("")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| 🔴 Critical | {report.critical_count} |")
    lines.append(f"| 🟠 Major | {report.major_count} |")
    lines.append(f"| 🟡 Minor | {report.minor_count} |")
    lines.append(f"| 🔵 Advisory | {report.advisory_count} |")
    lines.append(f"| **Total** | **{report.total_findings}** |")
    lines.append("")

    # Detailed Findings by Severity
    for severity in ["CRITICAL", "MAJOR", "MINOR", "ADVISORY"]:
        severity_findings = [f for f in report.findings if f.severity == severity]
        if not severity_findings:
            continue

        emoji = {"CRITICAL": "🔴", "MAJOR": "🟠", "MINOR": "🟡", "ADVISORY": "🔵"}[severity]
        lines.append("---")
        lines.append(f"## {emoji} {severity} Findings ({len(severity_findings)})")
        lines.append("")

        for finding in severity_findings:
            lines.append(f"### {finding.finding_id}: {finding.title}")
            lines.append("")
            lines.append(f"**Document Section:** {finding.document_section}")
            lines.append("")
            lines.append(f"**Issue:** {finding.description}")
            lines.append("")
            lines.append(f"**Document States:**")
            lines.append(f"> {finding.document_text}")
            lines.append("")
            lines.append(f"**OSHA Requirement ({finding.regulation_reference}):**")
            lines.append(f"> {finding.regulation_requirement}")
            lines.append("")
            lines.append(f"**Recommended Action:** {finding.recommendation}")
            lines.append("")

    # Document Metadata
    if report.document_metadata:
        lines.append("---")
        lines.append("## Document Metadata")
        lines.append("")
        for key, value in report.document_metadata.items():
            readable_key = key.replace("_", " ").title()
            lines.append(f"- **{readable_key}:** {value}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Report generated by Safety Compliance Agent on {report.analysis_date}*")
    lines.append("")
    lines.append("*This report is generated by an AI-powered compliance analysis tool. ")
    lines.append("All findings should be reviewed by a qualified safety professional ")
    lines.append("before taking corrective action. This tool assists with — but does not ")
    lines.append("replace — professional regulatory compliance review.*")

    return "\n".join(lines)


def generate_json_report(report: ComplianceReport) -> str:
    """Generate a JSON compliance report."""
    return json.dumps(report.to_dict(), indent=2)


def _format_status_badge(status: str) -> str:
    """Format the compliance status as a readable badge."""
    badges = {
        "NON-COMPLIANT": "🔴 NON-COMPLIANT",
        "NON_COMPLIANT": "🔴 NON-COMPLIANT",
        "PARTIALLY_COMPLIANT": "🟡 PARTIALLY COMPLIANT",
        "PARTIALLY-COMPLIANT": "🟡 PARTIALLY COMPLIANT",
        "COMPLIANT": "🟢 COMPLIANT",
    }
    return badges.get(status.upper().replace(" ", "_"), f"⚪ {status}")


def save_report(report: ComplianceReport, output_dir: str, formats: list = None) -> dict:
    """
    Save the compliance report to files.
    
    Args:
        report: The ComplianceReport to save
        output_dir: Directory to save report files
        formats: List of formats to generate ('markdown', 'json'). Defaults to both.
    
    Returns:
        Dict mapping format names to file paths
    """
    import os
    os.makedirs(output_dir, exist_ok=True)

    if formats is None:
        formats = ["markdown", "json"]

    saved_files = {}
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"compliance_report_{timestamp}"

    if "markdown" in formats:
        md_path = os.path.join(output_dir, f"{base_name}.md")
        with open(md_path, "w") as f:
            f.write(generate_markdown_report(report))
        saved_files["markdown"] = md_path

    if "json" in formats:
        json_path = os.path.join(output_dir, f"{base_name}.json")
        with open(json_path, "w") as f:
            f.write(generate_json_report(report))
        saved_files["json"] = json_path

    return saved_files
